In [1]:
import os
import numpy as np
import nibabel as nib
from nibabel.testing import data_path
import matplotlib.pyplot as plt
import pandas as pd

# Our Main File which contains Voxels across 300 TRs

In [18]:
import json
 
# Opening JSON file
f = open('./group_roi-EAC_desc-exclude_lags.json',)
 
# returns JSON object as
# a dictionary
data = json.load(f)

In [3]:
data.keys()

dict_keys(['21styear', 'black', 'bronx', 'forgot', 'lucy', 'merlin', 'milkyway', 'notthefallintact', 'notthefalllongscram', 'notthefallshortscram', 'pieman', 'piemanpni', 'prettymouth', 'reach', 'shapesphysical', 'shapessocial', 'sherlock', 'slumlord', 'tunnel'])

# If we want only Early Auditory Cortex Labels

In [4]:
eac_L = np.load('./tpl-fsaverage6/tpl-fsaverage6_hemi-L_desc-EAC_mask.npy')
eac_R = np.load('./tpl-fsaverage6/tpl-fsaverage6_hemi-R_desc-EAC_mask.npy')

In [10]:
pieman_subj_eac_L = []
pieman_subj_eac_R = []
for i in np.arange(1, 83):
    try:
        if i<10:
            files = os.listdir('sub-00'+str(i)+'/func/')
        else:
            files = os.listdir('sub-0'+str(i)+'/func/')
        num_files = sum('pieman' in s for s in files)
        temp_L = []
        temp_R = []
        if num_files==12:
            runs = ''
            if i<10:
                data_L = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(data_L.darrays[j].data[eac_L])
                temp_R.append(data_R.darrays[j].data[eac_R])
        else:
            runs1 = 'run-1_'
            runs2 = 'run-2_'
            if i<10:
                data_L1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(np.mean([data_L1.darrays[j].data[eac_L], data_L2.darrays[j].data[eac_L]], axis=0))
                temp_R.append(np.mean([data_R1.darrays[j].data[eac_R], data_R2.darrays[j].data[eac_R]], axis=0))
        pieman_subj_eac_L.append(np.array(temp_L))
        pieman_subj_eac_R.append(np.array(temp_R))
    except:
        print(i)
        continue

In [11]:
pieman_subj_eac_L = np.array(pieman_subj_eac_L)
pieman_subj_eac_R = np.array(pieman_subj_eac_R)

In [12]:
np.save('pieman_eac_L_avg',pieman_subj_eac_L)
np.save('pieman_eac_R_avg',pieman_subj_eac_R)

# AAC Rois

In [38]:
pieman_subj_aac_L = []
pieman_subj_aac_R = []
for i in np.arange(1, 83):
    try:
        if i<10:
            files = os.listdir('sub-00'+str(i)+'/func/')
        else:
            files = os.listdir('sub-0'+str(i)+'/func/')
        num_files = sum('pieman' in s for s in files)
        
        temp_L = []
        temp_R = []
        if num_files==12:
            runs = ''
            if i<10:
                data_L = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(data_L.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]])
                temp_R.append(data_R.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]])
        else:
            runs1 = 'run-1_'
            runs2 = 'run-2_'
            if i<10:
                data_L1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(np.mean([data_L1.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]], data_L2.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]]], axis=0))
                temp_R.append(np.mean([data_R1.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]], data_R2.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]]], axis=0))
        pieman_subj_aac_L.append(np.array(temp_L))
        pieman_subj_aac_R.append(np.array(temp_R))
    except:
        print(i)
        continue

In [39]:
pieman_subj_aac_L = np.array(pieman_subj_aac_L)
pieman_subj_aac_R = np.array(pieman_subj_aac_R)

In [40]:
np.save('pieman_aac_L_avg',pieman_subj_aac_L)
np.save('pieman_aac_R_avg',pieman_subj_aac_R)

# TPOJ

In [56]:
pieman_subj_tpoj_L = []
pieman_subj_tpoj_R = []
for i in np.arange(1, 83):
    try:
        if i<10:
            files = os.listdir('sub-00'+str(i)+'/func/')
        else:
            files = os.listdir('sub-0'+str(i)+'/func/')
        num_files = sum('pieman' in s for s in files)
        
        temp_L = []
        temp_R = []
        if num_files==12:
            runs = ''
            if i<10:
                data_L = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(data_L.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]])
                temp_R.append(data_R.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]])
        else:
            runs1 = 'run-1_'
            runs2 = 'run-2_'
            if i<10:
                data_L1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(np.mean([data_L1.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]], data_L2.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]]], axis=0))
                temp_R.append(np.mean([data_R1.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]], data_R2.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]]], axis=0))
        pieman_subj_tpoj_L.append(np.array(temp_L))
        pieman_subj_tpoj_R.append(np.array(temp_R))
    except:
        print(i)
        continue

In [57]:
pieman_subj_tpoj_L = np.array(pieman_subj_tpoj_L)
pieman_subj_tpoj_R = np.array(pieman_subj_tpoj_R)

In [58]:
np.save('pieman_tpoj_L_avg',pieman_subj_tpoj_L)
np.save('pieman_tpoj_R_avg',pieman_subj_tpoj_R)

# PMC

In [78]:
pieman_subj_pmc_L = []
pieman_subj_pmc_R = []
for i in np.arange(1, 83):
    try:
        if i<10:
            files = os.listdir('sub-00'+str(i)+'/func/')
        else:
            files = os.listdir('sub-0'+str(i)+'/func/')
        num_files = sum('pieman' in s for s in files)
        
        temp_L = []
        temp_R = []
        if num_files==12:
            runs = ''
            if i<10:
                data_L = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(data_L.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]])
                temp_R.append(data_R.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]])
        else:
            runs1 = 'run-1_'
            runs2 = 'run-2_'
            if i<10:
                data_L1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(np.mean([data_L1.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]], data_L2.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]]], axis=0))
                temp_R.append(np.mean([data_R1.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]], data_R2.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]]], axis=0))
        pieman_subj_pmc_L.append(np.array(temp_L))
        pieman_subj_pmc_R.append(np.array(temp_R))
    except:
        print(i)
        continue

In [79]:
pieman_subj_pmc_L = np.array(pieman_subj_pmc_L)
pieman_subj_pmc_R = np.array(pieman_subj_pmc_R)

In [80]:
np.save('pieman_pmc_L_avg',pieman_subj_pmc_L)
np.save('pieman_pmc_R_avg',pieman_subj_pmc_R)

# Language

In [9]:
pieman_subj_LANc_L = []
pieman_subj_LANc_R = []
for i in np.arange(1, 83):
    try:
        if i<10:
            files = os.listdir('sub-00'+str(i)+'/func/')
        else:
            files = os.listdir('sub-0'+str(i)+'/func/')
        num_files = sum('pieman' in s for s in files)
        
        temp_L = []
        temp_R = []
        if num_files==12:
            runs = ''
            if i<10:
                data_L = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(data_L.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]])
                temp_R.append(data_R.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]])
        else:
            runs1 = 'run-1_'
            runs2 = 'run-2_'
            if i<10:
                data_L1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(np.mean([data_L1.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]], data_L2.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]]], axis=0))
                temp_R.append(np.mean([data_R1.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]], data_R2.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]]], axis=0))
        pieman_subj_LANc_L.append(np.array(temp_L))
        pieman_subj_LANc_R.append(np.array(temp_R))
    except:
        print(i)
        continue

In [11]:
pieman_subj_LAN_L = np.array(pieman_subj_LANc_L)
pieman_subj_LAN_R = np.array(pieman_subj_LANc_R)

In [12]:
np.save('pieman_LAN_L_avg',pieman_subj_LAN_L)
np.save('pieman_LAN_R_avg',pieman_subj_LAN_R)

# Visual ROIS

In [26]:
pieman_subj_vis_L = []
pieman_subj_vis_R = []
for i in np.arange(1, 83):
    try:
        if i<10:
            files = os.listdir('sub-00'+str(i)+'/func/')
        else:
            files = os.listdir('sub-0'+str(i)+'/func/')
        num_files = sum('pieman' in s for s in files)
        
        temp_L = []
        temp_R = []
        if num_files==12:
            runs = ''
            if i<10:
                data_L = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(data_L.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]])
                temp_R.append(data_R.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]])
        else:
            runs1 = 'run-1_'
            runs2 = 'run-2_'
            if i<10:
                data_L1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(np.mean([data_L1.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]], data_L2.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]]], axis=0))
                temp_R.append(np.mean([data_R1.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]], data_R2.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]]], axis=0))
        pieman_subj_vis_L.append(np.array(temp_L))
        pieman_subj_vis_R.append(np.array(temp_R))
    except:
        print(i)
        continue

In [27]:
pieman_subj_vis_L = np.array(pieman_subj_vis_L)
pieman_subj_vis_R = np.array(pieman_subj_vis_R)

In [28]:
np.save('pieman_vis_L_avg',pieman_subj_vis_L)
np.save('pieman_vis_R_avg',pieman_subj_vis_R)

In [127]:
print(pieman_subj_pmc_L.shape)

(82, 300, 1198)


In [3]:
data_L.print_summary()

----start----
Source filename:  None
Number of data arrays:  300
Version:  1.0
----
Metadata:
{'UniqueID': 'XYZ_BAgOpZN9FA95XM1M2uyOTQ', 'TimeStep': '0', 'AFNI_History': '[snastase@redshirt-n29: Mon Jul 20 22:37:45 2020] {AFNI_19.3.02:linux_openmp_64} 3dTproject -input /jukebox/hasson/snastase/narratives/derivatives/fmriprep/sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-L.func.gii -ort /jukebox/hasson/snastase/narratives/derivatives/afni-nosmooth/sub-001/func/sub-001_task-pieman_run-1_desc-model_regressors.1D -TR 1.5 -prefix /jukebox/hasson/snastase/narratives/derivatives/afni-nosmooth/sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_desc-clean.func.gii -polort 2;', 'gifticlib-version': 'gifti library version 1.16, 2 May, 2017'}
None
----
Labeltable:
{}
None
----
DataArray 0:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian

 [0. 0. 0. 1.]]
None
None
----
DataArray 71:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 72:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 73:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexing

 [0. 0. 0. 1.]]
None
None
----
DataArray 123:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 124:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 125:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndex

 [0. 0. 0. 1.]]
None
None
----
DataArray 198:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 199:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 200:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndex

 [0. 0. 0. 1.]]
None
None
----
DataArray 271:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 272:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 273:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndex

In [4]:
data_R.print_summary()

----start----
Source filename:  None
Number of data arrays:  300
Version:  1.0
----
Metadata:
{'UniqueID': 'XYZ_ItfSPtI3hksDBhdZgdWy1g', 'TimeStep': '0', 'AFNI_History': '[snastase@redshirt-n29: Mon Jul 20 22:37:38 2020] {AFNI_19.3.02:linux_openmp_64} 3dTproject -input /jukebox/hasson/snastase/narratives/derivatives/fmriprep/sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-R.func.gii -ort /jukebox/hasson/snastase/narratives/derivatives/afni-nosmooth/sub-001/func/sub-001_task-pieman_run-1_desc-model_regressors.1D -TR 1.5 -prefix /jukebox/hasson/snastase/narratives/derivatives/afni-nosmooth/sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-R_desc-clean.func.gii -polort 2;', 'gifticlib-version': 'gifti library version 1.16, 2 May, 2017'}
None
----
Labeltable:
{}
None
----
DataArray 0:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian

 [0. 0. 0. 1.]]
None
None
----
DataArray 58:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 59:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 60:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexing

 [0. 0. 0. 1.]]
None
None
----
DataArray 136:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 137:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 138:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndex

 [0. 0. 0. 1.]]
None
None
----
DataArray 216:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 217:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 218:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndex

 [0. 0. 0. 1.]]
None
None
----
DataArray 294:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 295:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndexingOrder:  RowMajorOrder
Dimensionality:  1
Dimensions:  [40962]
Encoding:  Base64Binary
Endian:  LittleEndian
ExternalFileName:  
ExternalFileOffset:  0
----
Coordinate System:
Dataspace:  NIFTI_XFORM_UNKNOWN
XFormSpace:  NIFTI_XFORM_UNKNOWN
Affine Transformation Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
None
None
----
DataArray 296:
Intent:  NIFTI_INTENT_TIME_SERIES
DataType:  NIFTI_TYPE_FLOAT32
ArrayIndex

# Whole Brain Labels

In [2]:
L_labels = nib.load('./tpl-fsaverage6/tpl-fsaverage6_hemi-L_desc-MMP_dseg.label.gii')
R_labels = nib.load('./tpl-fsaverage6/tpl-fsaverage6_hemi-R_desc-MMP_dseg.label.gii')

In [3]:
L_labels.get_labeltable().get_labels_as_dict()

<ipython-input-3-3df3d859602e>:1: DeprecationWarning: get_labeltable method deprecated. Use the gifti_img.labeltable property instead.

* deprecated from version: 2.1
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 4.0
  L_labels.get_labeltable().get_labels_as_dict()


{0: '???',
 1: 'L_V1_ROI',
 2: 'L_MST_ROI',
 3: 'L_V6_ROI',
 4: 'L_V2_ROI',
 5: 'L_V3_ROI',
 6: 'L_V4_ROI',
 7: 'L_V8_ROI',
 8: 'L_4_ROI',
 9: 'L_3b_ROI',
 10: 'L_FEF_ROI',
 11: 'L_PEF_ROI',
 12: 'L_55b_ROI',
 13: 'L_V3A_ROI',
 14: 'L_RSC_ROI',
 15: 'L_POS2_ROI',
 16: 'L_V7_ROI',
 17: 'L_IPS1_ROI',
 18: 'L_FFC_ROI',
 19: 'L_V3B_ROI',
 20: 'L_LO1_ROI',
 21: 'L_LO2_ROI',
 22: 'L_PIT_ROI',
 23: 'L_MT_ROI',
 24: 'L_A1_ROI',
 25: 'L_PSL_ROI',
 26: 'L_SFL_ROI',
 27: 'L_PCV_ROI',
 28: 'L_STV_ROI',
 29: 'L_7Pm_ROI',
 30: 'L_7m_ROI',
 31: 'L_POS1_ROI',
 32: 'L_23d_ROI',
 33: 'L_v23ab_ROI',
 34: 'L_d23ab_ROI',
 35: 'L_31pv_ROI',
 36: 'L_5m_ROI',
 37: 'L_5mv_ROI',
 38: 'L_23c_ROI',
 39: 'L_5L_ROI',
 40: 'L_24dd_ROI',
 41: 'L_24dv_ROI',
 42: 'L_7AL_ROI',
 43: 'L_SCEF_ROI',
 44: 'L_6ma_ROI',
 45: 'L_7Am_ROI',
 46: 'L_7PL_ROI',
 47: 'L_7PC_ROI',
 48: 'L_LIPv_ROI',
 49: 'L_VIP_ROI',
 50: 'L_MIP_ROI',
 51: 'L_1_ROI',
 52: 'L_2_ROI',
 53: 'L_3a_ROI',
 54: 'L_6d_ROI',
 55: 'L_6mp_ROI',
 56: 'L_6v_ROI',


In [4]:
R_labels.get_labeltable().get_labels_as_dict()

<ipython-input-4-97ea1ef4219f>:1: DeprecationWarning: get_labeltable method deprecated. Use the gifti_img.labeltable property instead.

* deprecated from version: 2.1
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 4.0
  R_labels.get_labeltable().get_labels_as_dict()


{0: '???',
 1: 'R_V1_ROI',
 2: 'R_MST_ROI',
 3: 'R_V6_ROI',
 4: 'R_V2_ROI',
 5: 'R_V3_ROI',
 6: 'R_V4_ROI',
 7: 'R_V8_ROI',
 8: 'R_4_ROI',
 9: 'R_3b_ROI',
 10: 'R_FEF_ROI',
 11: 'R_PEF_ROI',
 12: 'R_55b_ROI',
 13: 'R_V3A_ROI',
 14: 'R_RSC_ROI',
 15: 'R_POS2_ROI',
 16: 'R_V7_ROI',
 17: 'R_IPS1_ROI',
 18: 'R_FFC_ROI',
 19: 'R_V3B_ROI',
 20: 'R_LO1_ROI',
 21: 'R_LO2_ROI',
 22: 'R_PIT_ROI',
 23: 'R_MT_ROI',
 24: 'R_A1_ROI',
 25: 'R_PSL_ROI',
 26: 'R_SFL_ROI',
 27: 'R_PCV_ROI',
 28: 'R_STV_ROI',
 29: 'R_7Pm_ROI',
 30: 'R_7m_ROI',
 31: 'R_POS1_ROI',
 32: 'R_23d_ROI',
 33: 'R_v23ab_ROI',
 34: 'R_d23ab_ROI',
 35: 'R_31pv_ROI',
 36: 'R_5m_ROI',
 37: 'R_5mv_ROI',
 38: 'R_23c_ROI',
 39: 'R_5L_ROI',
 40: 'R_24dd_ROI',
 41: 'R_24dv_ROI',
 42: 'R_7AL_ROI',
 43: 'R_SCEF_ROI',
 44: 'R_6ma_ROI',
 45: 'R_7Am_ROI',
 46: 'R_7PL_ROI',
 47: 'R_7PC_ROI',
 48: 'R_LIPv_ROI',
 49: 'R_VIP_ROI',
 50: 'R_MIP_ROI',
 51: 'R_1_ROI',
 52: 'R_2_ROI',
 53: 'R_3a_ROI',
 54: 'R_6d_ROI',
 55: 'R_6mp_ROI',
 56: 'R_6v_ROI',


In [29]:
data['tunnel']['L']['lagged ISCs'].keys()

dict_keys(['sub-001', 'sub-005', 'sub-022', 'sub-025', 'sub-026', 'sub-041', 'sub-052', 'sub-053', 'sub-055', 'sub-056', 'sub-057', 'sub-058', 'sub-059', 'sub-060', 'sub-061', 'sub-062', 'sub-063', 'sub-064', 'sub-065', 'sub-066', 'sub-069'])

In [30]:
data['lucy']['L']['lagged ISCs'].keys()

dict_keys(['sub-022', 'sub-026', 'sub-041', 'sub-052', 'sub-055', 'sub-056', 'sub-058', 'sub-059', 'sub-060', 'sub-061', 'sub-066', 'sub-069', 'sub-073', 'sub-074'])

In [34]:
data['reach']['L']['lagged ISCs'].keys()

dict_keys(['sub-016', 'sub-084', 'sub-106', 'sub-111', 'sub-132', 'sub-133', 'sub-134', 'sub-135', 'sub-136', 'sub-137', 'sub-138', 'sub-140', 'sub-141', 'sub-142', 'sub-143', 'sub-144', 'sub-145'])

In [81]:
AAC = ['A4', 'A5', 'STSdp', 'STSda', 'STSvp', 'STSva', 'STGa', "TA2" ]
AAC_Lindices = [175, 125, 128, 129, 130, 176, 123, 107]

In [5]:
TPOJ = ['TPOJ1', 'TPOJ2', 'TPOJ3', 'STV', 'PSL']
PMC = ['POS1', 'POS2', 'v23ab', 'd23ab', '31pv', '31pd', '7m']

In [6]:
TPOJ_indices = [139, 140, 141, 28, 25]
PMC_indices = [15, 30, 31, 33, 34, 35, 161]

In [127]:
LANG = ['L_55b', 'SFL', 'L_44', 'L_45', 'IFJA', 'IFSP']
LANG_indices = [12, 26, 74, 75, 79, 81]

In [8]:
L_labels.darrays[0].data[L_labels.darrays[0].data==1] = 0
R_labels.darrays[0].data[R_labels.darrays[0].data==1] = 0
for i in LANG_indices:
    L_labels.darrays[0].data[L_labels.darrays[0].data==i] = 1
    R_labels.darrays[0].data[R_labels.darrays[0].data==i] = 1
L_labels.darrays[0].data[L_labels.darrays[0].data!=1] = 0
R_labels.darrays[0].data[R_labels.darrays[0].data!=1] = 0

In [60]:
Visual = ['V1', 'V2', 'V3', 'V4', 'VMV1', 'VMV3', 'DVT', 'VMV2']
Visual_indices = [1, 4, 5, 6, 153, 154, 142, 160]
EAC_indices = [24,174,173,124,104]

In [23]:
#L_labels.darrays[0].data[L_labels.darrays[0].data==1] = 0
#R_labels.darrays[0].data[R_labels.darrays[0].data==1] = 0
for i in Visual_indices:
    L_labels.darrays[0].data[L_labels.darrays[0].data==i] = 1
    R_labels.darrays[0].data[R_labels.darrays[0].data==i] = 1
L_labels.darrays[0].data[L_labels.darrays[0].data!=1] = 0
R_labels.darrays[0].data[R_labels.darrays[0].data!=1] = 0

In [25]:
np.where(L_labels.darrays[0].data==1)[0].shape

(3115,)

In [148]:
L_labels = nib.load('./tpl-fsaverage6/tpl-fsaverage6_hemi-L_desc-MMP_dseg.label.gii')
R_labels = nib.load('./tpl-fsaverage6/tpl-fsaverage6_hemi-R_desc-MMP_dseg.label.gii')
L_labels.darrays[0].data[L_labels.darrays[0].data==1] = 0
R_labels.darrays[0].data[R_labels.darrays[0].data==1] = 0
for i in LANG_indices[5:6]:
    L_labels.darrays[0].data[L_labels.darrays[0].data==i] = 1
    R_labels.darrays[0].data[R_labels.darrays[0].data==i] = 1
L_labels.darrays[0].data[L_labels.darrays[0].data!=1] = 0
R_labels.darrays[0].data[R_labels.darrays[0].data!=1] = 0

In [149]:
pieman_subj_pmc_L = []
pieman_subj_pmc_R = []
for i in np.arange(1, 83):
    try:
        if i<10:
            files = os.listdir('sub-00'+str(i)+'/func/')
        else:
            files = os.listdir('sub-0'+str(i)+'/func/')
        num_files = sum('pieman' in s for s in files)
        
        temp_L = []
        temp_R = []
        if num_files==12:
            runs = ''
            if i<10:
                data_L = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(data_L.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]])
                temp_R.append(data_R.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]])
        else:
            runs1 = 'run-1_'
            runs2 = 'run-2_'
            if i<10:
                data_L1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-00'+str(i)+'/func/sub-00'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            else:
                data_L1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_L2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-L_desc-clean.func.gii')
                data_R1 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs1+'space-fsaverage6_hemi-R_desc-clean.func.gii')
                data_R2 = nib.load('sub-0'+str(i)+'/func/sub-0'+str(i)+'_task-pieman_'+runs2+'space-fsaverage6_hemi-R_desc-clean.func.gii')
            for j in np.arange(300):
                temp_L.append(np.mean([data_L1.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]], data_L2.darrays[j].data[np.where(L_labels.darrays[0].data==1)[0]]], axis=0))
                temp_R.append(np.mean([data_R1.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]], data_R2.darrays[j].data[np.where(R_labels.darrays[0].data==1)[0]]], axis=0))
        pieman_subj_pmc_L.append(np.array(temp_L))
        pieman_subj_pmc_R.append(np.array(temp_R))
    except:
        print(i)
        continue

In [150]:
pieman_subj_pmc_L = np.array(pieman_subj_pmc_L)
pieman_subj_pmc_R = np.array(pieman_subj_pmc_R)

In [151]:
np.save('./pmc_pieman/pieman_lan_L_ifsp',pieman_subj_pmc_L)
np.save('./pmc_pieman/pieman_lan_R_ifsp',pieman_subj_pmc_R)